"""drop indexes from invoice_shares

Revision ID: d78911203154
Revises: 6280fdd4b93f
Create Date: 2025-11-07 12:33:05.783859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd78911203154'
down_revision: Union[str, Sequence[str], None] = '6280fdd4b93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_shares_creditor_id'), table_name='invoice_shares')
    op.drop_index(op.f('ix_invoice_shares_debtor_id'), table_name='invoice_shares')
    op.drop_index(op.f('ix_invoice_shares_invoice_id'), table_name='invoice_shares')
    op.drop_index(op.f('ix_invoice_shares_status'), table_name='invoice_shares')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoice_shares_status'), 'invoice_shares', ['status'], unique=False)
    op.create_index(op.f('ix_invoice_shares_invoice_id'), 'invoice_shares', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_shares_debtor_id'), 'invoice_shares', ['debtor_id'], unique=False)
    op.create_index(op.f('ix_invoice_shares_creditor_id'), 'invoice_shares', ['creditor_id'], unique=False)
    # ### end Alembic commands ###
