"""update invoice share status enum

Revision ID: dee538493a4d
Revises: b2c3d4e5f6a7
Create Date: 2025-11-07 11:12:22.326268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dee538493a4d'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balances_user_id_key'), 'balances', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('balances_user_id_key'), 'balances', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
