"""add invoice and invoice_share tables

Revision ID: f6bc7013d957
Revises: 439a4bf1ecdb
Create Date: 2025-11-05 16:59:00.727139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f6bc7013d957"
down_revision: Union[str, Sequence[str], None] = "439a4bf1ecdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "type", sa.Enum("INDIVIDUAL", "GROUP", name="invoicetype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PARTIALLY_PAID", "PAID", "SETTLED", name="invoicestatus"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoices_creator_id"), "invoices", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "invoice_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("debtor_id", sa.Uuid(), nullable=False),
        sa.Column("creditor_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "WATING_CONFIRMATION",
                "CONFIRMED",
                "REJECTED",
                name="invoicesharestatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creditor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["debtor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_shares_creditor_id"),
        "invoice_shares",
        ["creditor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_shares_debtor_id"),
        "invoice_shares",
        ["debtor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_shares_invoice_id"),
        "invoice_shares",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_shares_status"), "invoice_shares", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_shares_status"), table_name="invoice_shares")
    op.drop_index(op.f("ix_invoice_shares_invoice_id"), table_name="invoice_shares")
    op.drop_index(op.f("ix_invoice_shares_debtor_id"), table_name="invoice_shares")
    op.drop_index(op.f("ix_invoice_shares_creditor_id"), table_name="invoice_shares")
    op.drop_table("invoice_shares")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_creator_id"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
